django_esp_project/django_esp_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^esp_game/', include('esp_game.urls', namespace="esp_game")),
]

django_esp_project/esp_game/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^start$', views.start_game, name='start_game'),
	url(r'^disconnected/(?P<game_id>[0-9]+)/$', views.game_disconnected, name='game_disconnected'),
	url(r'^ajax_submit_choice$', views.ajax_submit_choice, name='ajax_submit_choice'),
	url(r'^ajax_get_question/(?P<question_id>[0-9]+)/$', views.ajax_get_question, name='ajax_get_question')
]

django_esp_project/esp_game/models.py
from django.db import models

class BaseImage(models.Model):
	url = models.URLField()

	def __unicode__(self):
		return self.url
		
	class Meta:
		abstract = True

class PrimaryImage(BaseImage):
	pass

class SecondaryImage(BaseImage):
	primaryImage = models.ForeignKey(PrimaryImage)
	score = models.IntegerField(default=0)

class Game(models.Model):
	players = models.IntegerField(default=1)

	def __unicode__(self):
		return str(self.id) + ' ' + str(self.players)

class Question(models.Model):
	game = models.ForeignKey(Game)
	primaryImage = models.ForeignKey(PrimaryImage)
	firstPlayerChoice = models.IntegerField(blank=True, null=True)
	secondaryImage1 = models.ForeignKey(SecondaryImage, related_name="choice1", blank=True, null=True)
	secondaryImage2 = models.ForeignKey(SecondaryImage, related_name="choice2", blank=True, null=True)
	secondaryImage3 = models.ForeignKey(SecondaryImage, related_name="choice3", blank=True, null=True)

	def save(self, *args, **kwargs):
		secondaryImages = SecondaryImage.objects.filter(primaryImage=self.primaryImage).order_by('?')[:3]
		self.secondaryImage1, self.secondaryImage2, self.secondaryImage3 = secondaryImages
		super(Question, self).save(*args, **kwargs)

django_esp_project/esp_game/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from django.core import serializers
from django.conf import settings
from django.db.models import F
from .models import *

import requests 


socketURL = settings.SOCKET_URL

def index(request):
	return render(request, 'esp_game/index.html', {'home': True})

def start_game(request):
	print "start_game"
	old_game = Game.objects.filter(players=1).first()
	if old_game:
		print "old_game"
		old_game.players = F('players') + 1
		old_game.save()
		randomPrimaryImage = PrimaryImage.objects.order_by('?').first()
		firstQuestion = Question(game=old_game, primaryImage=randomPrimaryImage)
		firstQuestion.save()
		context = {
			'status': 'paired',
			'heading': 'Lets Play!',
			'game': old_game,
			'question': firstQuestion,
			'socketURL': socketURL
		}
		return render(request, 'esp_game/start.html', context)
	else:
		print "new_game"
		new_game = Game()
		new_game.save()
		context = {
			'heading': 'Waiting for Opponent to join',
			'game': new_game,
			'socketURL': socketURL
		}
		return render(request, 'esp_game/start.html', context)

def game_disconnected(request, game_id):
	print "game_disconnected"
	game = get_object_or_404(Game, pk=game_id)
	question = Question.objects.filter(game=game)
	question.delete()
	game.delete()
	return JsonResponse({"status": "OK"})

def ajax_submit_choice(request):
	print "ajax_submit_choice"
	questionId = request.POST.get('questionId')
	playerChoice = request.POST.get('playerChoice')
	curr_question = Question.objects.filter(id=questionId).first()

	if not curr_question:
		return JsonResponse({"status": "404"})

	if not curr_question.firstPlayerChoice:
		print "added_choice"
		curr_question.firstPlayerChoice = playerChoice
		curr_question.save()
		return JsonResponse({"status": "wait"})
	else:
		if str(curr_question.firstPlayerChoice) == str(playerChoice):
			print "choice matched"
			secondaryImage = SecondaryImage.objects.get(id=playerChoice)
			secondaryImage.score = F('score') + 1
			secondaryImage.save()
			randomPrimaryImage = PrimaryImage.objects.order_by('?').first()
			new_question = Question(game=curr_question.game, primaryImage=randomPrimaryImage)
			new_question.save()
			curr_question.delete()
			return JsonResponse({"status": "match", "newQuestion": new_question.id})
		else:
			print "choice did not match"
			curr_question.firstPlayerChoice = None
			curr_question.save()
			return JsonResponse({"status": "fail"})
			
def ajax_get_question(request, question_id):
	print "getting question"
	question = get_object_or_404(Question, pk=question_id)
	question_json = {
		'game': question.game.id,
		'primaryImage': question.primaryImage.url,
		'secondaryImage1': [question.secondaryImage1.id, question.secondaryImage1.url],
		'secondaryImage2': [question.secondaryImage2.id, question.secondaryImage2.url],
		'secondaryImage3': [question.secondaryImage3.id, question.secondaryImage3.url],
		'id': question.id
	}
	return JsonResponse({"question": question_json})

django_esp_project/esp_game/templates/esp_game/base.html
<!DOCTYPE html>
<html>
<head>
	{% load staticfiles %}
	<title>ESP Fun!</title>	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="{% static 'esp_game/cover.css' %}">
	<link rel="stylesheet" href="{% static 'esp_game/mystyle.css' %}">
	{% block head_scripts %} {% endblock %}
</head>
<body>
	<div class="alert">
	      
      </div>
	<div class="site-wrapper">
		<div class="site-wrapper-inner">
			<div class="cover-container">
				<div class="masthead clearfix">
					<div class="inner">
						<h3 class="masthead-brand">ESP Game for Matching Images</h3>
						<nav>
								<ul class="nav masthead-nav">
									<li {% if home %}class="active"{% endif %}><a href="{% url 'esp_game:index' %}">Home</a></li>
									<li><a href="https://github.com/ketanbhatt/esp-match-images">Github</a></li>
								</ul>
				              </nav>
					</div>
			      </div>
				{% block body_custom %} {% endblock %}
				<div class="mastfoot">
					<div class="inner">
						<p>Made for <a href="https://squadrun.co/">SquadRun</a>, by <a href="https://github.com/ketanbhatt">#ketanbhatt</a>.</p>
					</div>
			      </div>
			</div>
		</div>
	</div>

</body>
</html>

django_esp_project/esp_game/templates/esp_game/index.html
{% extends "esp_game/base.html" %}

{% block body_custom %}
	<form action="{% url 'esp_game:start_game' %}">
		<input type="submit" value="Press to Create/Join a game" class="btn btn-default">
	</form>
{% endblock %}

django_esp_project/esp_game/templates/esp_game/start.html
{% extends "esp_game/base.html" %}

{% block head_scripts %}
<script src="https://cdn.socket.io/socket.io-1.2.0.js"></script>
<script>
	var gameNum
	var totalTime = 0
	var tempTime = 0
	var socket = io('{{ socketURL }}');
	var channel = "{{ game.id }}"
	var status = "{{ status }}"
	socket.emit('join', {channel: channel});
	if(status == 'paired') {
		socket.emit('paired_server', {question: "{{ question.id }}", heading: "{{ heading }}"});
		gameNum = 1
		tempTime = new Date().getTime()
	}
	socket.on("paired", function(data) {
		gameNum = 1
		tempTime = new Date().getTime()
		var heading = data.heading
		var url_mask = "{% url 'esp_game:ajax_get_question' 12345 %}".replace(/12345/, data.question.toString());
		$.get( url_mask)
			.done(function( data ) {
				var newForm = generate_form(data.question)
				$("#heading").text(heading);
				$("#heading").after(newForm)
			});
	});
	socket.on("player_waiting", function() {
		$(".alert").html("<h5 id='message'>Opponent submitted his answer</h5>");
	});
	socket.on("answers_match", function(data) {
		tempTime = new Date().getTime()
		console.log("match " + totalTime)
		alert("Answers Matched!")
		if(gameNum == 2) {
			alert("You clocked in at " + totalTime + " seconds.")
			var url_mask= "{% url 'esp_game:index' %}"
			window.location.replace(url_mask);
		} else {
			gameNum += 1
			var url_mask = "{% url 'esp_game:ajax_get_question' 12345 %}".replace(/12345/, data.newQuestion.toString());
			$.get( url_mask)
				.done(function( data ) {
					var newForm = generate_form(data.question)
					$("#makeChoice").replaceWith(newForm)
					$("#message").remove()
				});
		}
	});
	socket.on("match_fail", function() {
		totalTime -= tempTime
		console.log("fail " + totalTime)
		tempTime = new Date().getTime()
		alert("Answers didn't match, try again")
		$("#message").remove()
		$("#makeChoice").trigger('reset');
		$("#makeChoice div").last().after('<input type="submit" value="Submit" id="submit" class="btn btn-primary">')
	});
	socket.on("player_disconnect", function(data) {
		if(gameNum != 2) {
			alert("Opponent disconnected from the game, the game will now end");
			var url_mask= "{% url 'esp_game:index' %}"
			window.location.replace(url_mask);			
		}
	});

	$(document).ready(function() {
		$("body").on('submit', '#makeChoice', function (event) {
			event.preventDefault();
			var now = new Date().getTime()
			tempTime = (now - tempTime)/1000
			totalTime += tempTime
			var playerChoice = $("#makeChoice").serializeArray()[0].value
			var questionId = $("#question").attr("value")
			var req_data = {
				'playerChoice': playerChoice,
				'questionId': questionId,
				'csrfmiddlewaretoken': '{{ csrf_token }}'
			}
			$.post( "{% url 'esp_game:ajax_submit_choice' %}", req_data)
				.done(function( data) {
					$("#submit").remove()
					if(data.status == "404") {
						alert("The game was disconnected")
						var url_mask= "{% url 'esp_game:index' %}"
						window.location.replace(url_mask);
					}else if (data.status == "wait") {
						$(".alert").html("<h5 id='message'>Waiting for opponent</h5>");
						socket.emit('player_waiting_server', {channel: channel});
					} else if(data.status == "match") {
						socket.emit('answers_match_server', {channel: channel, newQuestion: data.newQuestion});
					} else if(data.status == "fail") {
						socket.emit('match_fail_server', {channel: channel});
					}
				});
		});
	})

	var generate_form = function(question) {
		var data = question
		var newForm = '<form action="#" id="makeChoice">\
				<div class="row">\
					<div class="col-md-3"></div>\
					<div class="col-md-6">\
						<img id="question" src="'+ data.primaryImage +'" alt="Primary Image" value="'+ data.id +'" class="primaryImage img-responsive">\
					</div>\
					<div class="col-md-3"></div>\
				</div>\
				<br>\
				<div class="row">\
					<div class="col-md-4">\
						<label class="radio-img">\
							<input type="radio" name="playerChoice" value="'+ data.secondaryImage1[0] +'"><img src="'+ data.secondaryImage1[1] +'" alt="Secondary Image 1" class="secondaryImage img-responsive">\
						</label>\
					</div>\
					<div class="col-md-4">\
						<label class="radio-img">\
							<input type="radio" name="playerChoice" value="'+ data.secondaryImage2[0] +'"><img src="'+ data.secondaryImage2[1] +'" alt="Secondary Image 2" class="secondaryImage img-responsive">\
						</label>\
					</div>\
					<div class="col-md-4">\
						<label class="radio-img">\
							<input type="radio" name="playerChoice" value="'+ data.secondaryImage3[0] +'"><img src="'+ data.secondaryImage3[1] +'" alt="Secondary Image 3" class="secondaryImage img-responsive">\
						</label>\
					</div>\
				</div>\
				<input type="submit" value="Submit" id="submit" class="btn btn-primary">\
			</form>'
		return newForm
	}
</script>
{% endblock %}

{% block body_custom %}
	<div class="inner cover">
		<h1 id="heading" class="cover-heading">{{ heading }}</h1>
			{% if status == 'paired' %}
			<form action="#" id="makeChoice">
				<div class="row">
					<div class="col-md-3"></div>
					<div class="col-md-6">
						<img id="question" src="{{ question.primaryImage.url }}" alt="Primary Image" value="{{ question.id }}" class="primaryImage img-responsive">
					</div>
					<div class="col-md-3"></div>
				</div>	
				<br>
				<div class="row">
					<div class="col-md-4">
						<label class="radio-img">
							<input type="radio" name="playerChoice" value="{{ question.secondaryImage1.id }}"><img src="{{ question.secondaryImage1.url }}" alt="Secondary Image 1" class="secondaryImage img-responsive">
						</label>
					</div>
					<div class="col-md-4">
						<label class="radio-img">
							<input type="radio" name="playerChoice" value="{{ question.secondaryImage2.id }}"><img src="{{ question.secondaryImage2.url }}" alt="Secondary Image 2" class="secondaryImage img-responsive">
						</label>
					</div>
					<div class="col-md-4">
						<label class="radio-img">
							<input type="radio" name="playerChoice" value="{{ question.secondaryImage3.id }}"><img src="{{ question.secondaryImage3.url }}" alt="Secondary Image 3" class="secondaryImage img-responsive">
						</label>
					</div>
				</div>

				<input type="submit" value="Submit" id="submit" class="btn btn-primary">
			</form>
			{% endif %}
	</div>

{% endblock %}

django_esp_project/esp_game/templates/esp_game/wait_game.html
<script src="https://cdn.socket.io/socket.io-1.2.0.js"></script>
<script>
	var socket = io('http://0.0.0.0:3000');
	socket.emit('join', {email: 'user1@example.com'});
	socket.on("new_msg", function(data) {
	    alert(data.msg);
	});
</script>
<h4>Waiting for another player to join</h4>
<a href="{% url 'esp_game:index' %}">go back</a>